export const REQUEST_LATEST_PRICES = 'REQUEST_PRICES';
export const RECEIVE_LATEST_PRICES = 'RECEIVE_PRICES';

export const REQUEST_HISTORY = 'REQUEST_HISTORY';
export const RECEIVE_HISTORY = 'RECEIVE_HISTORY';

export const RECEIVE_NEW_PRICE = 'RECEIVE_NEW_PRICE';
